dataset: fc100
data_root: /root/INFUSE/database

n_way: 5
k_shot: 1
q_query: 15
num_test_episodes: 1000
batch_size: 128
num_workers: 4

feature_dim: 640
# cosine, euclidean
metric: cosine
classifier_temperature: 1.0

# resnet, swin
image_backbone: resnet
image_encoder_ckpt: database/checkpoints/ResNet-FC100.pth
# bert, clip-vit
text_backbone: bert

test_ckpt_path: checkpoints/infuse_best.pth


